--liquibase formatted sql

--changeset hezix:1
create table if not exists users
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) with time zone,
    email      varchar(255),
    first_name varchar(32),
    last_name  varchar(32),
    password   varchar(255),
    image       varchar(255),
    role       varchar(16),
    username   varchar(32)
);
--changeset hezix:2
create table if not exists albums
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    title       varchar(255),
    image       varchar(255),
    type        varchar(32),
    created_at  timestamp(6) with time zone not null,
    author_id   bigint
        constraint fk_albums_user_id
            references users
);
--changeset hezix:3
create table if not exists songs
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone not null,
    created_by  varchar(32),
    description varchar(64),
    title       varchar(32),
    image       varchar(255),
    song_file   varchar(255),
    genre       varchar(16),
    author_id   bigint
        constraint fk_songs_author_id
            references users,
    album_id    bigint
        constraint fk_songs_album_id
            references albums
);
--changeset hezix:4
create table liked_songs
(
    user_id bigint not null
        constraint fk_liked_songs_user_id
            references users,
    song_id bigint not null
        constraint fk_liked_songs_song_id
            references songs,
    primary key (user_id, song_id)
);

--changeset hezix:5
create table playlists
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) with time zone not null,
    image      varchar(255),
    title      varchar(255),
    type       varchar(32),
    author     bigint
        constraint fk_playlists_user_id
            references users
);
--changeset hezix:6
create table playlist_songs
(
    playlist_id bigint not null
        constraint fk_playlist_songs_playlist_id
            references playlists,
    song_id     bigint not null
        constraint fk_playlist_songs_song_id
            references songs
);
--changeset hezix:7
create table liked_playlists
(
    user_id     bigint not null
        constraint fk_liked_playlists_user_id
            references users,
    playlist_id bigint not null
        constraint fk_liked_playlists_playlist_id
            references playlists,
    primary key (user_id, playlist_id)
);