--liquibase formatted sql

--changeset hezix:1
create table if not exists users
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) with time zone,
    email      varchar(255),
    first_name varchar(32),
    last_name  varchar(32),
    password   varchar(255),
    role       varchar(16),
    username   varchar(32)
);
--changeset hezix:2
create table if not exists songs
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone not null,
    created_by  varchar(32),
    description varchar(64),
    title       varchar(32),
    genre       varchar(16),
    author_id   bigint
        constraint fk_songs_author_id
            references users,
    album_id    bigint
        constraint fk_songs_album_id
            references albums
);
--changeset hezix:3
create table if not exists liked_songs
(
    id      bigint not null
        primary key,
    song_id bigint
        constraint fk_liked_songs_song_id
            references songs,
    user_id bigint
        constraint fk_liked_songs_user_id
            references users
);
--changeset hezix:4
create table if not exists albums
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    title       varchar(255),
    created_at  timestamp(6) with time zone not null,
    author_id   bigint
        constraint fk_albums_user_id
            references users
);